// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.Data.Models;

public partial class Cliente
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("NIF")]
    [StringLength(9)]
    [Unicode(false)]
    public string Nif { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("morada")]
    [StringLength(50)]
    [Unicode(false)]
    public string Morada { get; set; }

    [Required]
    [Column("concelho")]
    [StringLength(50)]
    [Unicode(false)]
    public string Concelho { get; set; }

    [Required]
    [Column("distrito")]
    [StringLength(50)]
    [Unicode(false)]
    public string Distrito { get; set; }

    [InverseProperty("IdClientesNavigation")]
    public virtual ICollection<LivrosCliente> LivrosClientes { get; set; } = new List<LivrosCliente>();
}