// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.Data.Models;

public partial class ControleEmprestimoLivrosContext : DbContext
{
    public ControleEmprestimoLivrosContext()
    {
    }

    public ControleEmprestimoLivrosContext(DbContextOptions<ControleEmprestimoLivrosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Livro> Livros { get; set; }

    public virtual DbSet<LivrosCliente> LivrosClientes { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=\"JSSICA-ALMEIDA\\SQLEXPRESS\";Initial Catalog=ControleEmprestimoLivros;Integrated Security=True; TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LivrosCliente>(entity =>
        {
            entity.HasOne(d => d.IdClientesNavigation).WithMany(p => p.LivrosClientes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Livros_Clientes_Clientes");

            entity.HasOne(d => d.IdLivrosNavigation).WithMany(p => p.LivrosClientes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Livros_Clientes_Livros");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}