// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.Data.Models;

[Table("Livros_Clientes")]
public partial class LivrosCliente
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("idLivros")]
    public int IdLivros { get; set; }

    [Column("idClientes")]
    public int IdClientes { get; set; }

    [Column("dataEmprestimo")]
    public DateTime DataEmprestimo { get; set; }

    [Column("dataDevolucao")]
    public DateTime DataDevolucao { get; set; }

    [ForeignKey("IdClientes")]
    [InverseProperty("LivrosClientes")]
    public virtual Cliente IdClientesNavigation { get; set; }

    [ForeignKey("IdLivros")]
    [InverseProperty("LivrosClientes")]
    public virtual Livro IdLivrosNavigation { get; set; }
}